version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:delegated
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - PRISMA_MIGRATE_SKIP_GENERATE=true

    env_file:
      - .env
    command: sh -c "npx prisma generate && npx prisma migrate dev && nodemon --legacy-watch  --ext js,json,prisma server.js"
    restart: unless-stopped
